[project]
name = "JeffEngine"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "0.1.0"
authors = ["The Jeff Paradox Collaboration"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
julia = "1.9"
HTTP = "1"
JSON3 = "1"
YAML = "0.4"
